### ISSUE TITLE
ASPLOS'22: New exercise for software adaptation

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/cheri-exercises#43]
As we talked about today, it would be very nice to have an additional, less adversarial exercise focused on the kinds of common adaptations needed to port C to CHERI C.  Ideally something with N sins all found by the compiler and then 1 found only at runtime and 1 (possibly the same) found by the sanitizer.

**Comment by kwitaszczyk** [comment]
The exercise was added in https://github.com/CTSRD-CHERI/cheri-exercises/commit/c3f0c71a0dd132119b62698b806c8ea3219ca197.
