### ISSUE TITLE
New constructive exercise adapting a trivial heap allocator

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/cheri-exercises#44]
As we discussed today, it would be very nice if there were a "constructive" exercise, say, adapting a trivial heap allocator to CHERI, with the point being to add the csetbounds (and ponder crrl and maybe cram) and the non-monotonic reach to metadata.  This may be too long for ASPLOS'22 proper (or too much work to develop in time), but I think @davidchisnall at least indicated some willingness to write up a little C++ allocator for this purpose?

**Comment by rwatson** [comment]
I'd be tempted to drive it through a few test cases:
- Are bounds set correctly for a small allocation?
- Are bounds set correctly for a large allocation, with suitable padding, etc? If we use a simple allocator type, we could do a series of allocations and check for potential aliasing issue -- vs a more complex allocator.
- Does free work without crashing :-)

**Comment by nwf** [comment]
We should add this exercise, but I think it's a bit much for ASPLOS.

**Comment by nwf** [comment]
@rwatson wrote one in 0d98ab3994edbf95a3590142213615b9c7f7fc19.
